// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';


class EmployeesModel {
  final int id;
  final String name;
  final String job;
  final String admissionDate;
  final String phone;
  final String image;

  const EmployeesModel({
    required this.id,
    required this.name,
    required this.job,
    required this.admissionDate,
    required this.phone,
    required this.image,
  });

  EmployeesModel copyWith({
    int? id,
    String? name,
    String? job,
    String? admissionDate,
    String? phone,
    String? image,
  }) {
    return EmployeesModel(
      id: id ?? this.id,
      name: name ?? this.name,
      job: job ?? this.job,
      admissionDate: admissionDate ?? this.admissionDate,
      phone: phone ?? this.phone,
      image: image ?? this.image,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'job': job,
      'admissionDate': admissionDate,
      'phone': phone,
      'image': image,
    };
  }

  factory EmployeesModel.fromMap(Map<String, dynamic> map) {
     T cast<T>(String k) => map[k] is T ? map[k] as T : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return EmployeesModel(
      id: cast<num>('id').toInt(),
      name: cast<String>('name'),
      job: cast<String>('job'),
      admissionDate: cast<String>('admissionDate'),
      phone: cast<String>('phone'),
      image: cast<String>('image'),
    );
  }

  String toJson() => json.encode(toMap());

  factory EmployeesModel.fromJson(String source) => EmployeesModel.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'EmployeesModel(id: $id, name: $name, job: $job, admissionDate: $admissionDate, phone: $phone, image: $image)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
  
    return other is EmployeesModel &&
      other.id == id &&
      other.name == name &&
      other.job == job &&
      other.admissionDate == admissionDate &&
      other.phone == phone &&
      other.image == image;
  }

  @override
  int get hashCode {
    return id.hashCode ^
      name.hashCode ^
      job.hashCode ^
      admissionDate.hashCode ^
      phone.hashCode ^
      image.hashCode;
  }
}
